auth:
  jwt:
    secret: ${JWT_SECRET:}
spring:
  quartz:
    scheduler-name: quartz_
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
  batch:
    jdbc:
      initialize-schema: always
      table-prefix: BATCH_
    job:
      enabled: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    url: ${DB_URL:}
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate.order_inserts: true
      hibernate.order_updates: true
  elasticsearch:
    rest:
      username: ${ELASTIC_USERNAME}
      password: ${ELASTIC_PASSWORD}
      uris: ${ELASTIC_URL}
openapi:
  secret: ${OPENAPI_SECRET}
  kkyeongki:
    secret: ${KKYEONGKI_SECRET}