spring:
  batch:
    jdbc:
      initialize-schema: always
      table-prefix: batch_
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    url: ${DB_URL:}
    jackson:
      property-naming-strategy: SNAKE_CASE
    main:
      allow-bean-definition-overriding: true
    jpa:
      generate-ddl: false
      show-sql: false
      hibernate:
        use-new-id-generator-mappings: false
  elasticsearch:
    rest:
      username: ${ELASTIC_USERNAME}
      password: ${ELASTIC_PASSWORD}
      uris: ${ELASTIC_URL}
